In [103]:
from google.colab import files
upload = files.upload()

Saving DataPrepFinal.csv to DataPrepFinal (1).csv

In [104]:
import pandas as pd
import numpy as np

In [105]:
df = pd.read_csv("DataPrepFinal.csv")

In [106]:
df.head()
# coluna Unnamed: 0 provavelmente seria um id porém o pandas já cria esse campo então pode remover

,Unnamed: 0,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
0,0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,09/10/15,100000,11/08/15 12:12,0,failed,0,GB,0.0,0,USD 153395
1,1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,01/11/17,3000000,02/09/17 04:43,242100,failed,15,US,10000.0,242100,USD 3000000
2,2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,26/02/13,4500000,12/01/13 00:20,22000,failed,3,US,22000.0,22000,USD 4500000
3,3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,16/04/12,500000,17/03/12 03:24,100,failed,1,US,100.0,100,USD 500000
4,4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,29/08/15,1950000,04/07/15 08:35,128300,canceled,14,US,128300.0,128300,USD 1950000

In [107]:
# Aqui ele faz a remoção dos dados que ele não acha relevante. Ex o goal está em varios tipos de moeda e tem a coluna usd_goal_real que está tudo em dolar
# O que torna a analise mais facil pois está comparando tudo da mesma moeda. Mesmo caso no pledged.
df = df.drop(columns=['Unnamed: 0','name','category', 'goal','pledged','usd pledged'])

In [108]:
df.head()

,ID,main_category,currency,deadline,launched,state,backers,country,usd_pledged_real,usd_goal_real
0,1000002330,Publishing,GBP,09/10/15,11/08/15 12:12,failed,0,GB,0,USD 153395
1,1000003930,Film & Video,USD,01/11/17,02/09/17 04:43,failed,15,US,242100,USD 3000000
2,1000004038,Film & Video,USD,26/02/13,12/01/13 00:20,failed,3,US,22000,USD 4500000
3,1000007540,Music,USD,16/04/12,17/03/12 03:24,failed,1,US,100,USD 500000
4,1000011046,Film & Video,USD,29/08/15,04/07/15 08:35,canceled,14,US,128300,USD 1950000

In [109]:
df.head()

,ID,main_category,currency,deadline,launched,state,backers,country,usd_pledged_real,usd_goal_real
0,1000002330,Publishing,GBP,09/10/15,11/08/15 12:12,failed,0,GB,0,USD 153395
1,1000003930,Film & Video,USD,01/11/17,02/09/17 04:43,failed,15,US,242100,USD 3000000
2,1000004038,Film & Video,USD,26/02/13,12/01/13 00:20,failed,3,US,22000,USD 4500000
3,1000007540,Music,USD,16/04/12,17/03/12 03:24,failed,1,US,100,USD 500000
4,1000011046,Film & Video,USD,29/08/15,04/07/15 08:35,canceled,14,US,128300,USD 1950000

In [110]:
df.dtypes

ID                   int64
main_category       object
currency            object
deadline            object
launched            object
state               object
backers              int64
country             object
usd_pledged_real     int64
usd_goal_real       object
dtype: object

In [111]:
# Nessa função ele pega uma coluna e aplica algo que ele queira.
#Lambda é um indicativo de que eu vou criar minha propria função, não existe uma função especifica. Então vou criar.
# x é cada um dos valores de cada linha. 
#Strip é uma função do pandas para strings onde ela vai remover algo no começo (leading) ou no final (trailing) 
df['usd_goal_real'] = df['usd_goal_real'].apply(lambda x: x.lstrip('USD '))

df2['usd_goal_real'] = quando coloco essa função antes eu informo que quero que a minha coluna que eu apliquei a minha função permaneça com as minhas modificações.

In [112]:
df.head()

,ID,main_category,currency,deadline,launched,state,backers,country,usd_pledged_real,usd_goal_real
0,1000002330,Publishing,GBP,09/10/15,11/08/15 12:12,failed,0,GB,0,153395
1,1000003930,Film & Video,USD,01/11/17,02/09/17 04:43,failed,15,US,242100,3000000
2,1000004038,Film & Video,USD,26/02/13,12/01/13 00:20,failed,3,US,22000,4500000
3,1000007540,Music,USD,16/04/12,17/03/12 03:24,failed,1,US,100,500000
4,1000011046,Film & Video,USD,29/08/15,04/07/15 08:35,canceled,14,US,128300,1950000

In [113]:
#Regex, É uma expressão reguralar que é uma sequencia de caracteres que é generico o suficiente para identificar um padrão.
# df2['launched'].str.replace('12:12', '') --> se quisesse remover só de uma linha mas aqui também tem um padrão
df['launched'] = df['launched'].str.replace(' \d\d:\d\d', '', regex=True)
# Nesse caso ele vai remover o padrão espaço digito numerico (2x) : (2x). E depois substiruir por nada.

In [114]:
df.head()

,ID,main_category,currency,deadline,launched,state,backers,country,usd_pledged_real,usd_goal_real
0,1000002330,Publishing,GBP,09/10/15,11/08/15,failed,0,GB,0,153395
1,1000003930,Film & Video,USD,01/11/17,02/09/17,failed,15,US,242100,3000000
2,1000004038,Film & Video,USD,26/02/13,12/01/13,failed,3,US,22000,4500000
3,1000007540,Music,USD,16/04/12,17/03/12,failed,1,US,100,500000
4,1000011046,Film & Video,USD,29/08/15,04/07/15,canceled,14,US,128300,1950000

In [115]:
df.dtypes

ID                   int64
main_category       object
currency            object
deadline            object
launched            object
state               object
backers              int64
country             object
usd_pledged_real     int64
usd_goal_real       object
dtype: object

In [116]:
#Essa função serve para modificar o tipo do objeto nesse caso está mudando de object para int64
df['usd_goal_real'] = df ['usd_goal_real'].astype('int64')

In [117]:
df.dtypes

ID                   int64
main_category       object
currency            object
deadline            object
launched            object
state               object
backers              int64
country             object
usd_pledged_real     int64
usd_goal_real        int64
dtype: object

In [118]:
#Lendo a função seria mudar a coluna deadline para o tipo datetime
df['deadline'] = pd.to_datetime(df['deadline'], format='%d/%m/%y')
df['launched'] = pd.to_datetime(df['launched'], format='%d/%m/%y')

In [119]:
df.dtypes

ID                           int64
main_category               object
currency                    object
deadline            datetime64[ns]
launched            datetime64[ns]
state                       object
backers                      int64
country                     object
usd_pledged_real             int64
usd_goal_real                int64
dtype: object

In [120]:
#Aqui eu já consegui calcular os dias
df['time_range'] = (df['deadline']- df['launched']).dt.days

#E antes eu crio uma coluna que vai receber esse calculo no caso time_range

In [121]:
df.head()

,ID,main_category,currency,deadline,launched,state,backers,country,usd_pledged_real,usd_goal_real,time_range
0,1000002330,Publishing,GBP,2015-10-09,2015-08-11,failed,0,GB,0,153395,59
1,1000003930,Film & Video,USD,2017-11-01,2017-09-02,failed,15,US,242100,3000000,60
2,1000004038,Film & Video,USD,2013-02-26,2013-01-12,failed,3,US,22000,4500000,45
3,1000007540,Music,USD,2012-04-16,2012-03-17,failed,1,US,100,500000,30
4,1000011046,Film & Video,USD,2015-08-29,2015-07-04,canceled,14,US,128300,1950000,56

In [122]:
df.dtypes

ID                           int64
main_category               object
currency                    object
deadline            datetime64[ns]
launched            datetime64[ns]
state                       object
backers                      int64
country                     object
usd_pledged_real             int64
usd_goal_real                int64
time_range                   int64
dtype: object

In [123]:
from google.colab import files
upload = files.upload()

Saving campaign.csv to campaign (1).csv

In [124]:
#Dataframe de campanha, são dados relacionados a campanha.
df_c = pd.read_csv('campaign.csv')

In [125]:
df_c.head()

           ID  Text Description  Video  Image  Infographic  Reviews  Risks
0  1000002330                 1      1      1            1        0      1
1  1000003930                 1      1      1            1        1      0
2  1000004038                 1      0      1            1        0      1
3  1000007540                 1      1      0            1        0      0
4  1000011046                 1      0      1            0        0      0

In [126]:
#Esse código mostra quais são os valores unicos presentes na description, nesse caso só vai ter 1.
df_c['Text Description'].unique()

array([1])

In [127]:
# Como é um dado que todo mundo tem, não é interesante deixar na nossa analise.
df_c = df_c.drop(columns=['Text Description'])

In [128]:
df_c.head()

           ID  Video  Image  Infographic  Reviews  Risks
0  1000002330      1      1            1        0      1
1  1000003930      1      1            1        1      0
2  1000004038      0      1            1        0      1
3  1000007540      1      0            1        0      0
4  1000011046      0      1            0        0      0

In [129]:
df.head()

,ID,main_category,currency,deadline,launched,state,backers,country,usd_pledged_real,usd_goal_real,time_range
0,1000002330,Publishing,GBP,2015-10-09,2015-08-11,failed,0,GB,0,153395,59
1,1000003930,Film & Video,USD,2017-11-01,2017-09-02,failed,15,US,242100,3000000,60
2,1000004038,Film & Video,USD,2013-02-26,2013-01-12,failed,3,US,22000,4500000,45
3,1000007540,Music,USD,2012-04-16,2012-03-17,failed,1,US,100,500000,30
4,1000011046,Film & Video,USD,2015-08-29,2015-07-04,canceled,14,US,128300,1950000,56

In [130]:
# Vou dar um merge no dataset C a direita baseando pela coluna ID
df = df.merge(df_c, how='right', on =['ID'])

In [131]:
df.head()

,ID,main_category,currency,deadline,launched,state,backers,country,usd_pledged_real,usd_goal_real,time_range,Video,Image,Infographic,Reviews,Risks
0,1000002330,Publishing,GBP,2015-10-09,2015-08-11,failed,0,GB,0,153395,59,1,1,1,0,1
1,1000003930,Film & Video,USD,2017-11-01,2017-09-02,failed,15,US,242100,3000000,60,1,1,1,1,0
2,1000004038,Film & Video,USD,2013-02-26,2013-01-12,failed,3,US,22000,4500000,45,0,1,1,0,1
3,1000007540,Music,USD,2012-04-16,2012-03-17,failed,1,US,100,500000,30,1,0,1,0,0
4,1000011046,Film & Video,USD,2015-08-29,2015-07-04,canceled,14,US,128300,1950000,56,0,1,0,0,0

In [132]:
from google.colab import files
upload = files.upload()

Saving invested.csv to invested (1).csv

In [133]:
df_invest = pd.read_csv('invested.csv')

In [134]:
df_invest.head()

           ID backedLocation  age
0  1000003930             BR   18
1  1000004038             US   57
2  1000007540             US   43
3  1000011046             BR   29
4  1000014025             BR   77

In [135]:
df_invest.sort_values(by=['ID'])

               ID backedLocation  age
27400      106144             US   63
10585      106144            GBK   70
17409     1003381             BR   68
594       1003381             US   29
2925      1017454             US   62
...           ...            ...  ...
16812  1098729640            GBK   61
33627  1098729640            GBK   43
16814  1098735707             BR   66
33629  1098735707             US   62
35395  1098735707             US   63

[35396 rows x 3 columns]

In [141]:
# Nesse caso os dados estavam dificies de trabalhar tendo casos com o mesmo id mas com estados diferentes.
df_invest.head()

           ID backedLocation  age
0  1000003930             BR   18
1  1000004038             US   57
2  1000007540             US   43
3  1000011046             BR   29
4  1000014025             BR   77

In [142]:
#Aqui vai usar o One hot incode vai transformar as colunas em variaveis boleanas.
# Ele pegou as colunas e gerou uma categoria para cada uma delas e transformou o valor em boleano.
df_invest = pd.get_dummies(df_invest,columns=['backedLocation'])

In [143]:
df_invest.head()

           ID  age  backedLocation_BR  backedLocation_GBK  backedLocation_US
0  1000003930   18                  1                   0                  0
1  1000004038   57                  0                   0                  1
2  1000007540   43                  0                   0                  1
3  1000011046   29                  1                   0                  0
4  1000014025   77                  1                   0                  0

In [144]:
df_invest.sort_values(by=['ID'])

,ID,age,backedLocation_BR,backedLocation_GBK,backedLocation_US
27400,106144,63,0,0,1
10585,106144,70,0,1,0
17409,1003381,68,1,0,0
594,1003381,29,0,0,1
2925,1017454,62,0,0,1
...,...,...,...,...,...
16812,1098729640,61,0,1,0
33627,1098729640,43,0,1,0
16814,1098735707,66,1,0,0
33629,1098735707,62,0,0,1
35395,1098735707,63,0,0,1

In [146]:
#Nesse caso ele deu um group by e depois fez uma agregação com o agg
# No age usou a media no backedlocation usou soma.
df_invest = df_invest.groupby(by=['ID']).agg({'age':'mean','backedLocation_BR':'sum','backedLocation_GBK':'sum','backedLocation_US': 'sum'})

In [147]:
df_invest.head()

          age  backedLocation_BR  backedLocation_GBK  backedLocation_US
ID
106144   66.5                  0                   1                  1
1003381  48.5                  1                   0                  1
1017454  41.5                  0                   0                  2
1024013  77.0                  2                   0                  0
1024208  71.0                  0                   1                  1

In [149]:
#Aqui ele juntou as colunas todas do lado direito.
df = df.merge(df_invest, how='right', on='ID')

In [150]:
df.head()

,ID,main_category,currency,deadline,launched,state,backers,country,usd_pledged_real,usd_goal_real,time_range,Video,Image,Infographic,Reviews,Risks,age,backedLocation_BR,backedLocation_GBK,backedLocation_US
0,106144,Music,USD,2014-06-15,2014-05-16,failed,1,US,1500,180000,30,1,1,0,0,1,66.5,0,1,1
1,1003381,Music,USD,2012-07-19,2012-06-21,failed,30,US,115900,1000000,28,0,1,0,1,1,48.5,1,0,1
2,1017454,Film & Video,USD,2015-04-26,2015-04-20,successful,9,US,16700,100,6,1,0,1,0,1,41.5,0,0,2
3,1024013,Publishing,USD,2012-05-18,2012-04-03,failed,136,US,975805,4000000,45,1,1,1,0,0,77.0,2,0,0
4,1024208,Technology,USD,2014-09-11,2014-08-12,failed,5,US,15000,150000,30,0,1,1,0,0,71.0,0,1,1